version: '3.9'

services:
  redis-node-1:
    image: redis:6.2.10-alpine
    restart: always
    container_name: redis-node-1
    volumes:
      - ./6379-node:/usr/local/etc/redis
    network_mode: host
    command: 'redis-server /usr/local/etc/redis/redis.conf'

  redis-node-2:
    image: redis:6.2.10-alpine
    restart: always
    container_name: redis-node-2
    volumes:
      - ./6380-node:/usr/local/etc/redis
    network_mode: host
    command: 'redis-server /usr/local/etc/redis/redis.conf'

  redis-node-3:
    image: redis:6.2.10-alpine
    restart: always
    container_name: redis-node-3
    volumes:
      - ./6381-node:/usr/local/etc/redis
    network_mode: host
    command: 'redis-server /usr/local/etc/redis/redis.conf'

  redis-node-4:
    image: redis:6.2.10-alpine
    restart: always
    container_name: redis-node-4
    volumes:
      - ./6389-node:/usr/local/etc/redis
    network_mode: host
    command: 'redis-server /usr/local/etc/redis/redis.conf'

  redis-node-5:
    image: redis:6.2.10-alpine
    restart: always
    container_name: redis-node-5
    volumes:
      - ./6390-node:/usr/local/etc/redis
    network_mode: host
    command: 'redis-server /usr/local/etc/redis/redis.conf'

  redis-node-6:
    image: redis:6.2.10-alpine
    restart: always
    container_name: redis-node-6
    volumes:
      - ./6391-node:/usr/local/etc/redis
    network_mode: host
    command: 'redis-server /usr/local/etc/redis/redis.conf'
