version: 3.9

services:
  redis-master-1:
    #image: redis/redis-stack:6.2.6-v4
    image: redis:6.2.10-alpine
    restart: always
    container_name: redis-master-1
    volumes:
      - ./6379-master:/usr/local/etc/redis
    network_mode: host
    command: 'redis-server /usr/local/etc/redis/redis.conf'
  
  redis-master-2:
    #image: redis/redis-stack:6.2.6-v4
    image: redis:6.2.10-alpine
    restart: always
    container_name: redis-master-2
    volumes:
      - ./6380-master:/usr/local/etc/redis
    network_mode: host
    command: 'redis-server /usr/local/etc/redis/redis.conf'
  
  redis-master-3:
    #image: redis/redis-stack:6.2.6-v4
    image: redis:6.2.10-alpine
    restart: always
    container_name: redis-master-3
    volumes:
      - ./6381-master:/usr/local/etc/redis
    network_mode: host
    command: 'redis-server /usr/local/etc/redis/redis.conf'
  
  redis-replica-1:
    #image: redis/redis-stack:6.2.6-v4
    image: redis:6.2.10-alpine
    restart: always
    container_name: redis-replica-1
    volumes:
      - ./6389-replica:/usr/local/etc/redis
    network_mode: host
    command: 'redis-server /usr/local/etc/redis/redis.conf'
  
  redis-replica-2:
    #image: redis/redis-stack:6.2.6-v4
    image: redis:6.2.10-alpine
    restart: always
    container_name: redis-replica-2
    volumes:
      - ./6390-replica:/usr/local/etc/redis
    network_mode: host
    command: 'redis-server /usr/local/etc/redis/redis.conf'
  
  redis-replica-3:
    #image: redis/redis-stack:6.2.6-v4
    image: redis:6.2.10-alpine
    restart: always
    container_name: redis-replica-3
    volumes:
      - ./6391-replica:/usr/local/etc/redis
    network_mode: host
    command: 'redis-server /usr/local/etc/redis/redis.conf'

